Update AppGui.java
Evan-aja/Restaurant-Manager-SWT pull request #3
Opened 2021-05-10 12:50 UTC by miftahulihsan

2021-05-10 12:54 UTC, Evan-aja commented
> 

Jangan lupa kasih penjelasan disini juga, biar tau yang harus dicari yang mana

2021-05-10 13:00 UTC, miftahulihsan commented
Yang diubah:
-ditambah atribut jenisMenu di class abstrak Menu
-ditambah method getJenisMenu di class Makanan dan Minuman
-ditambah syarat ditambahnya makanan/minuman ke dalam list di dalam method panelTambahMenu

2021-05-11 00:59 UTC, Evan-aja commented on AppSource/App.java
> -    ArrayList<Minum> minumanArrayList;
San, untuk nama kelas nya bisa disamain sama gui? Soalnya di gui buat window nya ada yang namanya sama kayak source, dan kalau mau bikin kode sekalian di AppGui nya ya, yang disini gunanya buat dipindah ke gui, nanti dihapus package ini

2021-05-11 04:20 UTC, miftahulihsan commented
itu udah aku ubah ya vann

2021-05-11 04:57 UTC, Evan-aja requested changes
San, buat yang maksudnya dipindah ke gui itu bukan cli nya, maksudnya di implementasikan ke sini, jadi bukan full copy

2021-05-11 11:25 UTC, Evan-aja commented
broken

2021-05-11 11:28 UTC, closed without merging